version: '3.7'

networks:
  cassandra-app-network:
    driver: bridge

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-app-cassandra
    networks:
      - cassandra-app-network
    ports:
      - "29042:9042"
    environment:
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: cassandra-app-zookeeper
    networks:
      - cassandra-app-network
    ports:
      - "22181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: cassandra-app-kafka
    networks:
      - cassandra-app-network
    ports:
      - "29092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="Topic1:1:3,Topic2:1:2"
      - KAFKA_BROKER_ID=0
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
